server:
  port: 8081
spring:
  application:
    name: USER-SERVICE
  zipkin:
    base-url: http://localhost:9411
    enabled: true
eureka:
  client:
    service-url:
      defaultZone: 'http://localhost:8761/eureka'
resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
    instances:
      productServiceCB:
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
  retry:
    instances:
      productServiceRetry:
        max-attempts: 3
        wait-duration: 1s
        retryExceptions:
          - >-
            org.springframework.web.reactive.function.client.WebClientRequestException
          - >-
            org.springframework.web.reactive.function.client.WebClientResponseException
          - java.util.concurrent.TimeoutException
          - java.io.IOException

management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    export:
      prometheus:
        enabled: true
  health:
    circuitbreakers:
      enabled: true
  endpoint:
    health:
      show-details: always

